# Site settings
title: response-monitor.js
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  response-monitor.js
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oss.witstep.com/response-monitor.js" # the base hostname & protocol for your site
twitter_username: jorgemcpaulo
github_username:  witstep

# Build settings
markdown: kramdown
