# Site settings
title: response-monitor.js
baseurl: "/response-monitor.js/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  witstep
demo_url: http://as.witstep.com/oss/response-monitor.js/examples/service.php

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
